// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RecallService.proto

package slaughterhouse.grpc;

public interface AnimalsIdListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:slaughterhouse.grpc.AnimalsIdList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .slaughterhouse.grpc.AnimalId list = 1;</code>
   */
  java.util.List<slaughterhouse.grpc.AnimalId> 
      getListList();
  /**
   * <code>repeated .slaughterhouse.grpc.AnimalId list = 1;</code>
   */
  slaughterhouse.grpc.AnimalId getList(int index);
  /**
   * <code>repeated .slaughterhouse.grpc.AnimalId list = 1;</code>
   */
  int getListCount();
  /**
   * <code>repeated .slaughterhouse.grpc.AnimalId list = 1;</code>
   */
  java.util.List<? extends slaughterhouse.grpc.AnimalIdOrBuilder> 
      getListOrBuilderList();
  /**
   * <code>repeated .slaughterhouse.grpc.AnimalId list = 1;</code>
   */
  slaughterhouse.grpc.AnimalIdOrBuilder getListOrBuilder(
      int index);
}
