// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RecallService.proto

package slaughterhouse.grpc;

public interface ProductIdListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:slaughterhouse.grpc.ProductIdList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .slaughterhouse.grpc.ProductId list = 1;</code>
   */
  java.util.List<slaughterhouse.grpc.ProductId> 
      getListList();
  /**
   * <code>repeated .slaughterhouse.grpc.ProductId list = 1;</code>
   */
  slaughterhouse.grpc.ProductId getList(int index);
  /**
   * <code>repeated .slaughterhouse.grpc.ProductId list = 1;</code>
   */
  int getListCount();
  /**
   * <code>repeated .slaughterhouse.grpc.ProductId list = 1;</code>
   */
  java.util.List<? extends slaughterhouse.grpc.ProductIdOrBuilder> 
      getListOrBuilderList();
  /**
   * <code>repeated .slaughterhouse.grpc.ProductId list = 1;</code>
   */
  slaughterhouse.grpc.ProductIdOrBuilder getListOrBuilder(
      int index);
}
