// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RecallService.proto

package slaughterhouse.grpc;

public interface ProductIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:slaughterhouse.grpc.ProductId)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();
}
