// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RecallService.proto

package via.sdj3.grpcslaughterhouse.protobuf;

public interface AnimalListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:slaughterhouse.grpc.AnimalList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .slaughterhouse.grpc.AnimalMsg animals = 1;</code>
   */
  java.util.List<via.sdj3.grpcslaughterhouse.protobuf.AnimalMsg> 
      getAnimalsList();
  /**
   * <code>repeated .slaughterhouse.grpc.AnimalMsg animals = 1;</code>
   */
  via.sdj3.grpcslaughterhouse.protobuf.AnimalMsg getAnimals(int index);
  /**
   * <code>repeated .slaughterhouse.grpc.AnimalMsg animals = 1;</code>
   */
  int getAnimalsCount();
  /**
   * <code>repeated .slaughterhouse.grpc.AnimalMsg animals = 1;</code>
   */
  java.util.List<? extends via.sdj3.grpcslaughterhouse.protobuf.AnimalMsgOrBuilder> 
      getAnimalsOrBuilderList();
  /**
   * <code>repeated .slaughterhouse.grpc.AnimalMsg animals = 1;</code>
   */
  via.sdj3.grpcslaughterhouse.protobuf.AnimalMsgOrBuilder getAnimalsOrBuilder(
      int index);
}
