// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RecallService.proto

package via.sdj3.grpcslaughterhouse.protobuf;

public interface AnimalMsgOrBuilder extends
    // @@protoc_insertion_point(interface_extends:slaughterhouse.grpc.AnimalMsg)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float weight = 1;</code>
   * @return The weight.
   */
  float getWeight();

  /**
   * <code>string type = 2;</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <code>string type = 2;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>int32 id = 3;</code>
   * @return The id.
   */
  int getId();
}
