// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RecallService.proto

package via.sdj3.grpcslaughterhouse.protobuf;

public interface AnimalsIdListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:slaughterhouse.grpc.AnimalsIdList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .slaughterhouse.grpc.AnimalId list = 1;</code>
   */
  java.util.List<via.sdj3.grpcslaughterhouse.protobuf.AnimalId> 
      getListList();
  /**
   * <code>repeated .slaughterhouse.grpc.AnimalId list = 1;</code>
   */
  via.sdj3.grpcslaughterhouse.protobuf.AnimalId getList(int index);
  /**
   * <code>repeated .slaughterhouse.grpc.AnimalId list = 1;</code>
   */
  int getListCount();
  /**
   * <code>repeated .slaughterhouse.grpc.AnimalId list = 1;</code>
   */
  java.util.List<? extends via.sdj3.grpcslaughterhouse.protobuf.AnimalIdOrBuilder> 
      getListOrBuilderList();
  /**
   * <code>repeated .slaughterhouse.grpc.AnimalId list = 1;</code>
   */
  via.sdj3.grpcslaughterhouse.protobuf.AnimalIdOrBuilder getListOrBuilder(
      int index);
}
