// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RecallService.proto

package via.sdj3.grpcslaughterhouse.protobuf;

public interface animalsInProductResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:slaughterhouse.grpc.animalsInProductResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string trace = 1;</code>
   * @return The trace.
   */
  java.lang.String getTrace();
  /**
   * <code>string trace = 1;</code>
   * @return The bytes for trace.
   */
  com.google.protobuf.ByteString
      getTraceBytes();
}
