// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RecallService.proto

package via.sdj3.grpcslaughterhouse.protobuf;

public interface HalfAnimalMsgOrBuilder extends
    // @@protoc_insertion_point(interface_extends:slaughterhouse.grpc.HalfAnimalMsg)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string animalType = 1;</code>
   * @return The animalType.
   */
  java.lang.String getAnimalType();
  /**
   * <code>string animalType = 1;</code>
   * @return The bytes for animalType.
   */
  com.google.protobuf.ByteString
      getAnimalTypeBytes();
}
