// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RecallService.proto

package via.sdj3.grpcslaughterhouse.protobuf;

public interface PackRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:slaughterhouse.grpc.PackRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string filler = 1;</code>
   * @return The filler.
   */
  java.lang.String getFiller();
  /**
   * <code>string filler = 1;</code>
   * @return The bytes for filler.
   */
  com.google.protobuf.ByteString
      getFillerBytes();
}
