// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RecallService.proto

package via.sdj3.grpcslaughterhouse.protobuf;

/**
 * Protobuf type {@code slaughterhouse.grpc.PartMsg}
 */
public final class PartMsg extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:slaughterhouse.grpc.PartMsg)
    PartMsgOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PartMsg.newBuilder() to construct.
  private PartMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PartMsg() {
    partName_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PartMsg();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PartMsg(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            partId_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            partName_ = s;
            break;
          }
          case 29: {

            weight_ = input.readFloat();
            break;
          }
          case 34: {
            via.sdj3.grpcslaughterhouse.protobuf.AnimalMsg.Builder subBuilder = null;
            if (animal_ != null) {
              subBuilder = animal_.toBuilder();
            }
            animal_ = input.readMessage(via.sdj3.grpcslaughterhouse.protobuf.AnimalMsg.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(animal_);
              animal_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return via.sdj3.grpcslaughterhouse.protobuf.RecallService.internal_static_slaughterhouse_grpc_PartMsg_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return via.sdj3.grpcslaughterhouse.protobuf.RecallService.internal_static_slaughterhouse_grpc_PartMsg_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            via.sdj3.grpcslaughterhouse.protobuf.PartMsg.class, via.sdj3.grpcslaughterhouse.protobuf.PartMsg.Builder.class);
  }

  public static final int PARTID_FIELD_NUMBER = 1;
  private int partId_;
  /**
   * <code>int32 partId = 1;</code>
   * @return The partId.
   */
  @java.lang.Override
  public int getPartId() {
    return partId_;
  }

  public static final int PARTNAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object partName_;
  /**
   * <code>string partName = 2;</code>
   * @return The partName.
   */
  @java.lang.Override
  public java.lang.String getPartName() {
    java.lang.Object ref = partName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      partName_ = s;
      return s;
    }
  }
  /**
   * <code>string partName = 2;</code>
   * @return The bytes for partName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPartNameBytes() {
    java.lang.Object ref = partName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      partName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int WEIGHT_FIELD_NUMBER = 3;
  private float weight_;
  /**
   * <code>float weight = 3;</code>
   * @return The weight.
   */
  @java.lang.Override
  public float getWeight() {
    return weight_;
  }

  public static final int ANIMAL_FIELD_NUMBER = 4;
  private via.sdj3.grpcslaughterhouse.protobuf.AnimalMsg animal_;
  /**
   * <code>.slaughterhouse.grpc.AnimalMsg animal = 4;</code>
   * @return Whether the animal field is set.
   */
  @java.lang.Override
  public boolean hasAnimal() {
    return animal_ != null;
  }
  /**
   * <code>.slaughterhouse.grpc.AnimalMsg animal = 4;</code>
   * @return The animal.
   */
  @java.lang.Override
  public via.sdj3.grpcslaughterhouse.protobuf.AnimalMsg getAnimal() {
    return animal_ == null ? via.sdj3.grpcslaughterhouse.protobuf.AnimalMsg.getDefaultInstance() : animal_;
  }
  /**
   * <code>.slaughterhouse.grpc.AnimalMsg animal = 4;</code>
   */
  @java.lang.Override
  public via.sdj3.grpcslaughterhouse.protobuf.AnimalMsgOrBuilder getAnimalOrBuilder() {
    return getAnimal();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (partId_ != 0) {
      output.writeInt32(1, partId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(partName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, partName_);
    }
    if (java.lang.Float.floatToRawIntBits(weight_) != 0) {
      output.writeFloat(3, weight_);
    }
    if (animal_ != null) {
      output.writeMessage(4, getAnimal());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (partId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, partId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(partName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, partName_);
    }
    if (java.lang.Float.floatToRawIntBits(weight_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(3, weight_);
    }
    if (animal_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getAnimal());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof via.sdj3.grpcslaughterhouse.protobuf.PartMsg)) {
      return super.equals(obj);
    }
    via.sdj3.grpcslaughterhouse.protobuf.PartMsg other = (via.sdj3.grpcslaughterhouse.protobuf.PartMsg) obj;

    if (getPartId()
        != other.getPartId()) return false;
    if (!getPartName()
        .equals(other.getPartName())) return false;
    if (java.lang.Float.floatToIntBits(getWeight())
        != java.lang.Float.floatToIntBits(
            other.getWeight())) return false;
    if (hasAnimal() != other.hasAnimal()) return false;
    if (hasAnimal()) {
      if (!getAnimal()
          .equals(other.getAnimal())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PARTID_FIELD_NUMBER;
    hash = (53 * hash) + getPartId();
    hash = (37 * hash) + PARTNAME_FIELD_NUMBER;
    hash = (53 * hash) + getPartName().hashCode();
    hash = (37 * hash) + WEIGHT_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getWeight());
    if (hasAnimal()) {
      hash = (37 * hash) + ANIMAL_FIELD_NUMBER;
      hash = (53 * hash) + getAnimal().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static via.sdj3.grpcslaughterhouse.protobuf.PartMsg parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sdj3.grpcslaughterhouse.protobuf.PartMsg parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sdj3.grpcslaughterhouse.protobuf.PartMsg parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sdj3.grpcslaughterhouse.protobuf.PartMsg parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sdj3.grpcslaughterhouse.protobuf.PartMsg parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sdj3.grpcslaughterhouse.protobuf.PartMsg parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sdj3.grpcslaughterhouse.protobuf.PartMsg parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.sdj3.grpcslaughterhouse.protobuf.PartMsg parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.sdj3.grpcslaughterhouse.protobuf.PartMsg parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static via.sdj3.grpcslaughterhouse.protobuf.PartMsg parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.sdj3.grpcslaughterhouse.protobuf.PartMsg parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.sdj3.grpcslaughterhouse.protobuf.PartMsg parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(via.sdj3.grpcslaughterhouse.protobuf.PartMsg prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code slaughterhouse.grpc.PartMsg}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:slaughterhouse.grpc.PartMsg)
      via.sdj3.grpcslaughterhouse.protobuf.PartMsgOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return via.sdj3.grpcslaughterhouse.protobuf.RecallService.internal_static_slaughterhouse_grpc_PartMsg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return via.sdj3.grpcslaughterhouse.protobuf.RecallService.internal_static_slaughterhouse_grpc_PartMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              via.sdj3.grpcslaughterhouse.protobuf.PartMsg.class, via.sdj3.grpcslaughterhouse.protobuf.PartMsg.Builder.class);
    }

    // Construct using via.sdj3.grpcslaughterhouse.protobuf.PartMsg.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      partId_ = 0;

      partName_ = "";

      weight_ = 0F;

      if (animalBuilder_ == null) {
        animal_ = null;
      } else {
        animal_ = null;
        animalBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return via.sdj3.grpcslaughterhouse.protobuf.RecallService.internal_static_slaughterhouse_grpc_PartMsg_descriptor;
    }

    @java.lang.Override
    public via.sdj3.grpcslaughterhouse.protobuf.PartMsg getDefaultInstanceForType() {
      return via.sdj3.grpcslaughterhouse.protobuf.PartMsg.getDefaultInstance();
    }

    @java.lang.Override
    public via.sdj3.grpcslaughterhouse.protobuf.PartMsg build() {
      via.sdj3.grpcslaughterhouse.protobuf.PartMsg result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public via.sdj3.grpcslaughterhouse.protobuf.PartMsg buildPartial() {
      via.sdj3.grpcslaughterhouse.protobuf.PartMsg result = new via.sdj3.grpcslaughterhouse.protobuf.PartMsg(this);
      result.partId_ = partId_;
      result.partName_ = partName_;
      result.weight_ = weight_;
      if (animalBuilder_ == null) {
        result.animal_ = animal_;
      } else {
        result.animal_ = animalBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof via.sdj3.grpcslaughterhouse.protobuf.PartMsg) {
        return mergeFrom((via.sdj3.grpcslaughterhouse.protobuf.PartMsg)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(via.sdj3.grpcslaughterhouse.protobuf.PartMsg other) {
      if (other == via.sdj3.grpcslaughterhouse.protobuf.PartMsg.getDefaultInstance()) return this;
      if (other.getPartId() != 0) {
        setPartId(other.getPartId());
      }
      if (!other.getPartName().isEmpty()) {
        partName_ = other.partName_;
        onChanged();
      }
      if (other.getWeight() != 0F) {
        setWeight(other.getWeight());
      }
      if (other.hasAnimal()) {
        mergeAnimal(other.getAnimal());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      via.sdj3.grpcslaughterhouse.protobuf.PartMsg parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (via.sdj3.grpcslaughterhouse.protobuf.PartMsg) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int partId_ ;
    /**
     * <code>int32 partId = 1;</code>
     * @return The partId.
     */
    @java.lang.Override
    public int getPartId() {
      return partId_;
    }
    /**
     * <code>int32 partId = 1;</code>
     * @param value The partId to set.
     * @return This builder for chaining.
     */
    public Builder setPartId(int value) {
      
      partId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 partId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPartId() {
      
      partId_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object partName_ = "";
    /**
     * <code>string partName = 2;</code>
     * @return The partName.
     */
    public java.lang.String getPartName() {
      java.lang.Object ref = partName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        partName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string partName = 2;</code>
     * @return The bytes for partName.
     */
    public com.google.protobuf.ByteString
        getPartNameBytes() {
      java.lang.Object ref = partName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        partName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string partName = 2;</code>
     * @param value The partName to set.
     * @return This builder for chaining.
     */
    public Builder setPartName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      partName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string partName = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPartName() {
      
      partName_ = getDefaultInstance().getPartName();
      onChanged();
      return this;
    }
    /**
     * <code>string partName = 2;</code>
     * @param value The bytes for partName to set.
     * @return This builder for chaining.
     */
    public Builder setPartNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      partName_ = value;
      onChanged();
      return this;
    }

    private float weight_ ;
    /**
     * <code>float weight = 3;</code>
     * @return The weight.
     */
    @java.lang.Override
    public float getWeight() {
      return weight_;
    }
    /**
     * <code>float weight = 3;</code>
     * @param value The weight to set.
     * @return This builder for chaining.
     */
    public Builder setWeight(float value) {
      
      weight_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float weight = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearWeight() {
      
      weight_ = 0F;
      onChanged();
      return this;
    }

    private via.sdj3.grpcslaughterhouse.protobuf.AnimalMsg animal_;
    private com.google.protobuf.SingleFieldBuilderV3<
        via.sdj3.grpcslaughterhouse.protobuf.AnimalMsg, via.sdj3.grpcslaughterhouse.protobuf.AnimalMsg.Builder, via.sdj3.grpcslaughterhouse.protobuf.AnimalMsgOrBuilder> animalBuilder_;
    /**
     * <code>.slaughterhouse.grpc.AnimalMsg animal = 4;</code>
     * @return Whether the animal field is set.
     */
    public boolean hasAnimal() {
      return animalBuilder_ != null || animal_ != null;
    }
    /**
     * <code>.slaughterhouse.grpc.AnimalMsg animal = 4;</code>
     * @return The animal.
     */
    public via.sdj3.grpcslaughterhouse.protobuf.AnimalMsg getAnimal() {
      if (animalBuilder_ == null) {
        return animal_ == null ? via.sdj3.grpcslaughterhouse.protobuf.AnimalMsg.getDefaultInstance() : animal_;
      } else {
        return animalBuilder_.getMessage();
      }
    }
    /**
     * <code>.slaughterhouse.grpc.AnimalMsg animal = 4;</code>
     */
    public Builder setAnimal(via.sdj3.grpcslaughterhouse.protobuf.AnimalMsg value) {
      if (animalBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        animal_ = value;
        onChanged();
      } else {
        animalBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.slaughterhouse.grpc.AnimalMsg animal = 4;</code>
     */
    public Builder setAnimal(
        via.sdj3.grpcslaughterhouse.protobuf.AnimalMsg.Builder builderForValue) {
      if (animalBuilder_ == null) {
        animal_ = builderForValue.build();
        onChanged();
      } else {
        animalBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.slaughterhouse.grpc.AnimalMsg animal = 4;</code>
     */
    public Builder mergeAnimal(via.sdj3.grpcslaughterhouse.protobuf.AnimalMsg value) {
      if (animalBuilder_ == null) {
        if (animal_ != null) {
          animal_ =
            via.sdj3.grpcslaughterhouse.protobuf.AnimalMsg.newBuilder(animal_).mergeFrom(value).buildPartial();
        } else {
          animal_ = value;
        }
        onChanged();
      } else {
        animalBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.slaughterhouse.grpc.AnimalMsg animal = 4;</code>
     */
    public Builder clearAnimal() {
      if (animalBuilder_ == null) {
        animal_ = null;
        onChanged();
      } else {
        animal_ = null;
        animalBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.slaughterhouse.grpc.AnimalMsg animal = 4;</code>
     */
    public via.sdj3.grpcslaughterhouse.protobuf.AnimalMsg.Builder getAnimalBuilder() {
      
      onChanged();
      return getAnimalFieldBuilder().getBuilder();
    }
    /**
     * <code>.slaughterhouse.grpc.AnimalMsg animal = 4;</code>
     */
    public via.sdj3.grpcslaughterhouse.protobuf.AnimalMsgOrBuilder getAnimalOrBuilder() {
      if (animalBuilder_ != null) {
        return animalBuilder_.getMessageOrBuilder();
      } else {
        return animal_ == null ?
            via.sdj3.grpcslaughterhouse.protobuf.AnimalMsg.getDefaultInstance() : animal_;
      }
    }
    /**
     * <code>.slaughterhouse.grpc.AnimalMsg animal = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        via.sdj3.grpcslaughterhouse.protobuf.AnimalMsg, via.sdj3.grpcslaughterhouse.protobuf.AnimalMsg.Builder, via.sdj3.grpcslaughterhouse.protobuf.AnimalMsgOrBuilder> 
        getAnimalFieldBuilder() {
      if (animalBuilder_ == null) {
        animalBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            via.sdj3.grpcslaughterhouse.protobuf.AnimalMsg, via.sdj3.grpcslaughterhouse.protobuf.AnimalMsg.Builder, via.sdj3.grpcslaughterhouse.protobuf.AnimalMsgOrBuilder>(
                getAnimal(),
                getParentForChildren(),
                isClean());
        animal_ = null;
      }
      return animalBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:slaughterhouse.grpc.PartMsg)
  }

  // @@protoc_insertion_point(class_scope:slaughterhouse.grpc.PartMsg)
  private static final via.sdj3.grpcslaughterhouse.protobuf.PartMsg DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new via.sdj3.grpcslaughterhouse.protobuf.PartMsg();
  }

  public static via.sdj3.grpcslaughterhouse.protobuf.PartMsg getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PartMsg>
      PARSER = new com.google.protobuf.AbstractParser<PartMsg>() {
    @java.lang.Override
    public PartMsg parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PartMsg(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PartMsg> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PartMsg> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public via.sdj3.grpcslaughterhouse.protobuf.PartMsg getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

