// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RecallService.proto

package via.sdj3.grpcslaughterhouse.protobuf;

public interface PartListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:slaughterhouse.grpc.PartList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .slaughterhouse.grpc.PartMsg parts = 1;</code>
   */
  java.util.List<via.sdj3.grpcslaughterhouse.protobuf.PartMsg> 
      getPartsList();
  /**
   * <code>repeated .slaughterhouse.grpc.PartMsg parts = 1;</code>
   */
  via.sdj3.grpcslaughterhouse.protobuf.PartMsg getParts(int index);
  /**
   * <code>repeated .slaughterhouse.grpc.PartMsg parts = 1;</code>
   */
  int getPartsCount();
  /**
   * <code>repeated .slaughterhouse.grpc.PartMsg parts = 1;</code>
   */
  java.util.List<? extends via.sdj3.grpcslaughterhouse.protobuf.PartMsgOrBuilder> 
      getPartsOrBuilderList();
  /**
   * <code>repeated .slaughterhouse.grpc.PartMsg parts = 1;</code>
   */
  via.sdj3.grpcslaughterhouse.protobuf.PartMsgOrBuilder getPartsOrBuilder(
      int index);
}
