// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RecallService.proto

package via.sdj3.grpcslaughterhouse.protobuf;

public interface PartMsgOrBuilder extends
    // @@protoc_insertion_point(interface_extends:slaughterhouse.grpc.PartMsg)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 partId = 1;</code>
   * @return The partId.
   */
  int getPartId();

  /**
   * <code>string partName = 2;</code>
   * @return The partName.
   */
  java.lang.String getPartName();
  /**
   * <code>string partName = 2;</code>
   * @return The bytes for partName.
   */
  com.google.protobuf.ByteString
      getPartNameBytes();

  /**
   * <code>float weight = 3;</code>
   * @return The weight.
   */
  float getWeight();

  /**
   * <code>bool isInTray = 4;</code>
   * @return The isInTray.
   */
  boolean getIsInTray();

  /**
   * <code>bool isInProduct = 5;</code>
   * @return The isInProduct.
   */
  boolean getIsInProduct();

  /**
   * <code>.slaughterhouse.grpc.AnimalMsg animal = 6;</code>
   * @return Whether the animal field is set.
   */
  boolean hasAnimal();
  /**
   * <code>.slaughterhouse.grpc.AnimalMsg animal = 6;</code>
   * @return The animal.
   */
  via.sdj3.grpcslaughterhouse.protobuf.AnimalMsg getAnimal();
  /**
   * <code>.slaughterhouse.grpc.AnimalMsg animal = 6;</code>
   */
  via.sdj3.grpcslaughterhouse.protobuf.AnimalMsgOrBuilder getAnimalOrBuilder();
}
