// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RecallService.proto

package via.sdj3.grpcslaughterhouse.protobuf;

public interface ProductMsgOrBuilder extends
    // @@protoc_insertion_point(interface_extends:slaughterhouse.grpc.ProductMsg)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 productId = 1;</code>
   * @return The productId.
   */
  int getProductId();

  /**
   * <code>string productType = 2;</code>
   * @return The productType.
   */
  java.lang.String getProductType();
  /**
   * <code>string productType = 2;</code>
   * @return The bytes for productType.
   */
  com.google.protobuf.ByteString
      getProductTypeBytes();

  /**
   * <code>.slaughterhouse.grpc.TrayList trays = 3;</code>
   * @return Whether the trays field is set.
   */
  boolean hasTrays();
  /**
   * <code>.slaughterhouse.grpc.TrayList trays = 3;</code>
   * @return The trays.
   */
  via.sdj3.grpcslaughterhouse.protobuf.TrayList getTrays();
  /**
   * <code>.slaughterhouse.grpc.TrayList trays = 3;</code>
   */
  via.sdj3.grpcslaughterhouse.protobuf.TrayListOrBuilder getTraysOrBuilder();
}
