// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RecallService.proto

package via.sdj3.grpcslaughterhouse.protobuf;

public interface ProductListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:slaughterhouse.grpc.ProductList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .slaughterhouse.grpc.ProductMsg products = 1;</code>
   */
  java.util.List<via.sdj3.grpcslaughterhouse.protobuf.ProductMsg> 
      getProductsList();
  /**
   * <code>repeated .slaughterhouse.grpc.ProductMsg products = 1;</code>
   */
  via.sdj3.grpcslaughterhouse.protobuf.ProductMsg getProducts(int index);
  /**
   * <code>repeated .slaughterhouse.grpc.ProductMsg products = 1;</code>
   */
  int getProductsCount();
  /**
   * <code>repeated .slaughterhouse.grpc.ProductMsg products = 1;</code>
   */
  java.util.List<? extends via.sdj3.grpcslaughterhouse.protobuf.ProductMsgOrBuilder> 
      getProductsOrBuilderList();
  /**
   * <code>repeated .slaughterhouse.grpc.ProductMsg products = 1;</code>
   */
  via.sdj3.grpcslaughterhouse.protobuf.ProductMsgOrBuilder getProductsOrBuilder(
      int index);
}
