// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RecallService.proto

package via.sdj3.grpcslaughterhouse.protobuf;

public interface ProductIdListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:slaughterhouse.grpc.ProductIdList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .slaughterhouse.grpc.ProductId list = 1;</code>
   */
  java.util.List<via.sdj3.grpcslaughterhouse.protobuf.ProductId> 
      getListList();
  /**
   * <code>repeated .slaughterhouse.grpc.ProductId list = 1;</code>
   */
  via.sdj3.grpcslaughterhouse.protobuf.ProductId getList(int index);
  /**
   * <code>repeated .slaughterhouse.grpc.ProductId list = 1;</code>
   */
  int getListCount();
  /**
   * <code>repeated .slaughterhouse.grpc.ProductId list = 1;</code>
   */
  java.util.List<? extends via.sdj3.grpcslaughterhouse.protobuf.ProductIdOrBuilder> 
      getListOrBuilderList();
  /**
   * <code>repeated .slaughterhouse.grpc.ProductId list = 1;</code>
   */
  via.sdj3.grpcslaughterhouse.protobuf.ProductIdOrBuilder getListOrBuilder(
      int index);
}
