// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RecallService.proto

package via.sdj3.grpcslaughterhouse.protobuf;

public final class RecallServiceOuterClass {
  private RecallServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_slaughterhouse_grpc_AnimalId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_slaughterhouse_grpc_AnimalId_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_slaughterhouse_grpc_ProductId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_slaughterhouse_grpc_ProductId_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_slaughterhouse_grpc_AnimalsIdList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_slaughterhouse_grpc_AnimalsIdList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_slaughterhouse_grpc_ProductIdList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_slaughterhouse_grpc_ProductIdList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023RecallService.proto\022\023slaughterhouse.gr" +
      "pc\"\026\n\010AnimalId\022\n\n\002id\030\001 \001(\005\"\027\n\tProductId\022" +
      "\n\n\002id\030\001 \001(\005\"<\n\rAnimalsIdList\022+\n\004list\030\001 \003" +
      "(\0132\035.slaughterhouse.grpc.AnimalId\"=\n\rPro" +
      "ductIdList\022,\n\004list\030\001 \003(\0132\036.slaughterhous" +
      "e.grpc.ProductId2\300\001\n\rRecallService\022W\n\022pr" +
      "oductsWithAnimal\022\035.slaughterhouse.grpc.A" +
      "nimalId\032\".slaughterhouse.grpc.ProductIdL" +
      "ist\022V\n\020animalsInProduct\022\036.slaughterhouse" +
      ".grpc.ProductId\032\".slaughterhouse.grpc.An" +
      "imalsIdListB(\n$via.sdj3.grpcslaughterhou" +
      "se.protobufP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_slaughterhouse_grpc_AnimalId_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_slaughterhouse_grpc_AnimalId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_slaughterhouse_grpc_AnimalId_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_slaughterhouse_grpc_ProductId_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_slaughterhouse_grpc_ProductId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_slaughterhouse_grpc_ProductId_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_slaughterhouse_grpc_AnimalsIdList_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_slaughterhouse_grpc_AnimalsIdList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_slaughterhouse_grpc_AnimalsIdList_descriptor,
        new java.lang.String[] { "List", });
    internal_static_slaughterhouse_grpc_ProductIdList_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_slaughterhouse_grpc_ProductIdList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_slaughterhouse_grpc_ProductIdList_descriptor,
        new java.lang.String[] { "List", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
