// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RecallService.proto

package via.sdj3.grpcslaughterhouse.protobuf;

public final class RecallService {
  private RecallService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_slaughterhouse_grpc_AnimalMsg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_slaughterhouse_grpc_AnimalMsg_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_slaughterhouse_grpc_PartMsg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_slaughterhouse_grpc_PartMsg_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_slaughterhouse_grpc_PartList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_slaughterhouse_grpc_PartList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_slaughterhouse_grpc_TrayMsg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_slaughterhouse_grpc_TrayMsg_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_slaughterhouse_grpc_TrayList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_slaughterhouse_grpc_TrayList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_slaughterhouse_grpc_ProductMsg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_slaughterhouse_grpc_ProductMsg_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_slaughterhouse_grpc_ProductList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_slaughterhouse_grpc_ProductList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023RecallService.proto\022\023slaughterhouse.gr" +
      "pc\"5\n\tAnimalMsg\022\016\n\006weight\030\001 \001(\002\022\014\n\004type\030" +
      "\002 \001(\t\022\n\n\002id\030\003 \001(\005\"k\n\007PartMsg\022\016\n\006partId\030\001" +
      " \001(\005\022\020\n\010partName\030\002 \001(\t\022\016\n\006weight\030\003 \001(\002\022." +
      "\n\006animal\030\004 \001(\0132\036.slaughterhouse.grpc.Ani" +
      "malMsg\"7\n\010PartList\022+\n\005parts\030\001 \003(\0132\034.slau" +
      "ghterhouse.grpc.PartMsg\"q\n\007TrayMsg\022\016\n\006tr" +
      "ayId\030\001 \001(\005\022\026\n\016weightCapacity\030\002 \001(\002\022\020\n\010pa" +
      "rtName\030\003 \001(\t\022,\n\005parts\030\004 \001(\0132\035.slaughterh" +
      "ouse.grpc.PartList\"7\n\010TrayList\022+\n\005trays\030" +
      "\001 \003(\0132\034.slaughterhouse.grpc.TrayMsg\"b\n\nP" +
      "roductMsg\022\021\n\tproductId\030\001 \001(\005\022\023\n\013productT" +
      "ype\030\002 \001(\t\022,\n\005trays\030\003 \001(\0132\035.slaughterhous" +
      "e.grpc.TrayList\"@\n\013ProductList\0221\n\010produc" +
      "ts\030\001 \003(\0132\037.slaughterhouse.grpc.ProductMs" +
      "g2\333\002\n\025SlaughterhouseService\022P\n\016registerA" +
      "nimal\022\036.slaughterhouse.grpc.AnimalMsg\032\036." +
      "slaughterhouse.grpc.AnimalMsg\022J\n\tCutAnim" +
      "al\022\036.slaughterhouse.grpc.AnimalMsg\032\035.sla" +
      "ughterhouse.grpc.PartList\022L\n\014PackIntoTra" +
      "y\022\035.slaughterhouse.grpc.PartList\032\035.slaug" +
      "hterhouse.grpc.TrayList\022V\n\023PackForDistri" +
      "bution\022\035.slaughterhouse.grpc.TrayList\032 ." +
      "slaughterhouse.grpc.ProductListB(\n$via.s" +
      "dj3.grpcslaughterhouse.protobufP\001b\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_slaughterhouse_grpc_AnimalMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_slaughterhouse_grpc_AnimalMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_slaughterhouse_grpc_AnimalMsg_descriptor,
        new java.lang.String[] { "Weight", "Type", "Id", });
    internal_static_slaughterhouse_grpc_PartMsg_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_slaughterhouse_grpc_PartMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_slaughterhouse_grpc_PartMsg_descriptor,
        new java.lang.String[] { "PartId", "PartName", "Weight", "Animal", });
    internal_static_slaughterhouse_grpc_PartList_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_slaughterhouse_grpc_PartList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_slaughterhouse_grpc_PartList_descriptor,
        new java.lang.String[] { "Parts", });
    internal_static_slaughterhouse_grpc_TrayMsg_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_slaughterhouse_grpc_TrayMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_slaughterhouse_grpc_TrayMsg_descriptor,
        new java.lang.String[] { "TrayId", "WeightCapacity", "PartName", "Parts", });
    internal_static_slaughterhouse_grpc_TrayList_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_slaughterhouse_grpc_TrayList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_slaughterhouse_grpc_TrayList_descriptor,
        new java.lang.String[] { "Trays", });
    internal_static_slaughterhouse_grpc_ProductMsg_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_slaughterhouse_grpc_ProductMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_slaughterhouse_grpc_ProductMsg_descriptor,
        new java.lang.String[] { "ProductId", "ProductType", "Trays", });
    internal_static_slaughterhouse_grpc_ProductList_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_slaughterhouse_grpc_ProductList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_slaughterhouse_grpc_ProductList_descriptor,
        new java.lang.String[] { "Products", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
