// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RecallService.proto

package via.sdj3.grpcslaughterhouse.protobuf;

/**
 * Protobuf type {@code slaughterhouse.grpc.TrayMsg}
 */
public final class TrayMsg extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:slaughterhouse.grpc.TrayMsg)
    TrayMsgOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TrayMsg.newBuilder() to construct.
  private TrayMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TrayMsg() {
    partName_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TrayMsg();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TrayMsg(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            trayId_ = input.readInt32();
            break;
          }
          case 21: {

            weightCapacity_ = input.readFloat();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            partName_ = s;
            break;
          }
          case 34: {
            via.sdj3.grpcslaughterhouse.protobuf.PartList.Builder subBuilder = null;
            if (parts_ != null) {
              subBuilder = parts_.toBuilder();
            }
            parts_ = input.readMessage(via.sdj3.grpcslaughterhouse.protobuf.PartList.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(parts_);
              parts_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return via.sdj3.grpcslaughterhouse.protobuf.RecallService.internal_static_slaughterhouse_grpc_TrayMsg_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return via.sdj3.grpcslaughterhouse.protobuf.RecallService.internal_static_slaughterhouse_grpc_TrayMsg_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            via.sdj3.grpcslaughterhouse.protobuf.TrayMsg.class, via.sdj3.grpcslaughterhouse.protobuf.TrayMsg.Builder.class);
  }

  public static final int TRAYID_FIELD_NUMBER = 1;
  private int trayId_;
  /**
   * <code>int32 trayId = 1;</code>
   * @return The trayId.
   */
  @java.lang.Override
  public int getTrayId() {
    return trayId_;
  }

  public static final int WEIGHTCAPACITY_FIELD_NUMBER = 2;
  private float weightCapacity_;
  /**
   * <code>float weightCapacity = 2;</code>
   * @return The weightCapacity.
   */
  @java.lang.Override
  public float getWeightCapacity() {
    return weightCapacity_;
  }

  public static final int PARTNAME_FIELD_NUMBER = 3;
  private volatile java.lang.Object partName_;
  /**
   * <code>string partName = 3;</code>
   * @return The partName.
   */
  @java.lang.Override
  public java.lang.String getPartName() {
    java.lang.Object ref = partName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      partName_ = s;
      return s;
    }
  }
  /**
   * <code>string partName = 3;</code>
   * @return The bytes for partName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPartNameBytes() {
    java.lang.Object ref = partName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      partName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PARTS_FIELD_NUMBER = 4;
  private via.sdj3.grpcslaughterhouse.protobuf.PartList parts_;
  /**
   * <code>.slaughterhouse.grpc.PartList parts = 4;</code>
   * @return Whether the parts field is set.
   */
  @java.lang.Override
  public boolean hasParts() {
    return parts_ != null;
  }
  /**
   * <code>.slaughterhouse.grpc.PartList parts = 4;</code>
   * @return The parts.
   */
  @java.lang.Override
  public via.sdj3.grpcslaughterhouse.protobuf.PartList getParts() {
    return parts_ == null ? via.sdj3.grpcslaughterhouse.protobuf.PartList.getDefaultInstance() : parts_;
  }
  /**
   * <code>.slaughterhouse.grpc.PartList parts = 4;</code>
   */
  @java.lang.Override
  public via.sdj3.grpcslaughterhouse.protobuf.PartListOrBuilder getPartsOrBuilder() {
    return getParts();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (trayId_ != 0) {
      output.writeInt32(1, trayId_);
    }
    if (java.lang.Float.floatToRawIntBits(weightCapacity_) != 0) {
      output.writeFloat(2, weightCapacity_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(partName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, partName_);
    }
    if (parts_ != null) {
      output.writeMessage(4, getParts());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (trayId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, trayId_);
    }
    if (java.lang.Float.floatToRawIntBits(weightCapacity_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(2, weightCapacity_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(partName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, partName_);
    }
    if (parts_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getParts());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof via.sdj3.grpcslaughterhouse.protobuf.TrayMsg)) {
      return super.equals(obj);
    }
    via.sdj3.grpcslaughterhouse.protobuf.TrayMsg other = (via.sdj3.grpcslaughterhouse.protobuf.TrayMsg) obj;

    if (getTrayId()
        != other.getTrayId()) return false;
    if (java.lang.Float.floatToIntBits(getWeightCapacity())
        != java.lang.Float.floatToIntBits(
            other.getWeightCapacity())) return false;
    if (!getPartName()
        .equals(other.getPartName())) return false;
    if (hasParts() != other.hasParts()) return false;
    if (hasParts()) {
      if (!getParts()
          .equals(other.getParts())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TRAYID_FIELD_NUMBER;
    hash = (53 * hash) + getTrayId();
    hash = (37 * hash) + WEIGHTCAPACITY_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getWeightCapacity());
    hash = (37 * hash) + PARTNAME_FIELD_NUMBER;
    hash = (53 * hash) + getPartName().hashCode();
    if (hasParts()) {
      hash = (37 * hash) + PARTS_FIELD_NUMBER;
      hash = (53 * hash) + getParts().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static via.sdj3.grpcslaughterhouse.protobuf.TrayMsg parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sdj3.grpcslaughterhouse.protobuf.TrayMsg parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sdj3.grpcslaughterhouse.protobuf.TrayMsg parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sdj3.grpcslaughterhouse.protobuf.TrayMsg parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sdj3.grpcslaughterhouse.protobuf.TrayMsg parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sdj3.grpcslaughterhouse.protobuf.TrayMsg parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sdj3.grpcslaughterhouse.protobuf.TrayMsg parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.sdj3.grpcslaughterhouse.protobuf.TrayMsg parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.sdj3.grpcslaughterhouse.protobuf.TrayMsg parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static via.sdj3.grpcslaughterhouse.protobuf.TrayMsg parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.sdj3.grpcslaughterhouse.protobuf.TrayMsg parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.sdj3.grpcslaughterhouse.protobuf.TrayMsg parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(via.sdj3.grpcslaughterhouse.protobuf.TrayMsg prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code slaughterhouse.grpc.TrayMsg}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:slaughterhouse.grpc.TrayMsg)
      via.sdj3.grpcslaughterhouse.protobuf.TrayMsgOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return via.sdj3.grpcslaughterhouse.protobuf.RecallService.internal_static_slaughterhouse_grpc_TrayMsg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return via.sdj3.grpcslaughterhouse.protobuf.RecallService.internal_static_slaughterhouse_grpc_TrayMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              via.sdj3.grpcslaughterhouse.protobuf.TrayMsg.class, via.sdj3.grpcslaughterhouse.protobuf.TrayMsg.Builder.class);
    }

    // Construct using via.sdj3.grpcslaughterhouse.protobuf.TrayMsg.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      trayId_ = 0;

      weightCapacity_ = 0F;

      partName_ = "";

      if (partsBuilder_ == null) {
        parts_ = null;
      } else {
        parts_ = null;
        partsBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return via.sdj3.grpcslaughterhouse.protobuf.RecallService.internal_static_slaughterhouse_grpc_TrayMsg_descriptor;
    }

    @java.lang.Override
    public via.sdj3.grpcslaughterhouse.protobuf.TrayMsg getDefaultInstanceForType() {
      return via.sdj3.grpcslaughterhouse.protobuf.TrayMsg.getDefaultInstance();
    }

    @java.lang.Override
    public via.sdj3.grpcslaughterhouse.protobuf.TrayMsg build() {
      via.sdj3.grpcslaughterhouse.protobuf.TrayMsg result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public via.sdj3.grpcslaughterhouse.protobuf.TrayMsg buildPartial() {
      via.sdj3.grpcslaughterhouse.protobuf.TrayMsg result = new via.sdj3.grpcslaughterhouse.protobuf.TrayMsg(this);
      result.trayId_ = trayId_;
      result.weightCapacity_ = weightCapacity_;
      result.partName_ = partName_;
      if (partsBuilder_ == null) {
        result.parts_ = parts_;
      } else {
        result.parts_ = partsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof via.sdj3.grpcslaughterhouse.protobuf.TrayMsg) {
        return mergeFrom((via.sdj3.grpcslaughterhouse.protobuf.TrayMsg)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(via.sdj3.grpcslaughterhouse.protobuf.TrayMsg other) {
      if (other == via.sdj3.grpcslaughterhouse.protobuf.TrayMsg.getDefaultInstance()) return this;
      if (other.getTrayId() != 0) {
        setTrayId(other.getTrayId());
      }
      if (other.getWeightCapacity() != 0F) {
        setWeightCapacity(other.getWeightCapacity());
      }
      if (!other.getPartName().isEmpty()) {
        partName_ = other.partName_;
        onChanged();
      }
      if (other.hasParts()) {
        mergeParts(other.getParts());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      via.sdj3.grpcslaughterhouse.protobuf.TrayMsg parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (via.sdj3.grpcslaughterhouse.protobuf.TrayMsg) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int trayId_ ;
    /**
     * <code>int32 trayId = 1;</code>
     * @return The trayId.
     */
    @java.lang.Override
    public int getTrayId() {
      return trayId_;
    }
    /**
     * <code>int32 trayId = 1;</code>
     * @param value The trayId to set.
     * @return This builder for chaining.
     */
    public Builder setTrayId(int value) {
      
      trayId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 trayId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTrayId() {
      
      trayId_ = 0;
      onChanged();
      return this;
    }

    private float weightCapacity_ ;
    /**
     * <code>float weightCapacity = 2;</code>
     * @return The weightCapacity.
     */
    @java.lang.Override
    public float getWeightCapacity() {
      return weightCapacity_;
    }
    /**
     * <code>float weightCapacity = 2;</code>
     * @param value The weightCapacity to set.
     * @return This builder for chaining.
     */
    public Builder setWeightCapacity(float value) {
      
      weightCapacity_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float weightCapacity = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearWeightCapacity() {
      
      weightCapacity_ = 0F;
      onChanged();
      return this;
    }

    private java.lang.Object partName_ = "";
    /**
     * <code>string partName = 3;</code>
     * @return The partName.
     */
    public java.lang.String getPartName() {
      java.lang.Object ref = partName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        partName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string partName = 3;</code>
     * @return The bytes for partName.
     */
    public com.google.protobuf.ByteString
        getPartNameBytes() {
      java.lang.Object ref = partName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        partName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string partName = 3;</code>
     * @param value The partName to set.
     * @return This builder for chaining.
     */
    public Builder setPartName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      partName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string partName = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPartName() {
      
      partName_ = getDefaultInstance().getPartName();
      onChanged();
      return this;
    }
    /**
     * <code>string partName = 3;</code>
     * @param value The bytes for partName to set.
     * @return This builder for chaining.
     */
    public Builder setPartNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      partName_ = value;
      onChanged();
      return this;
    }

    private via.sdj3.grpcslaughterhouse.protobuf.PartList parts_;
    private com.google.protobuf.SingleFieldBuilderV3<
        via.sdj3.grpcslaughterhouse.protobuf.PartList, via.sdj3.grpcslaughterhouse.protobuf.PartList.Builder, via.sdj3.grpcslaughterhouse.protobuf.PartListOrBuilder> partsBuilder_;
    /**
     * <code>.slaughterhouse.grpc.PartList parts = 4;</code>
     * @return Whether the parts field is set.
     */
    public boolean hasParts() {
      return partsBuilder_ != null || parts_ != null;
    }
    /**
     * <code>.slaughterhouse.grpc.PartList parts = 4;</code>
     * @return The parts.
     */
    public via.sdj3.grpcslaughterhouse.protobuf.PartList getParts() {
      if (partsBuilder_ == null) {
        return parts_ == null ? via.sdj3.grpcslaughterhouse.protobuf.PartList.getDefaultInstance() : parts_;
      } else {
        return partsBuilder_.getMessage();
      }
    }
    /**
     * <code>.slaughterhouse.grpc.PartList parts = 4;</code>
     */
    public Builder setParts(via.sdj3.grpcslaughterhouse.protobuf.PartList value) {
      if (partsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        parts_ = value;
        onChanged();
      } else {
        partsBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.slaughterhouse.grpc.PartList parts = 4;</code>
     */
    public Builder setParts(
        via.sdj3.grpcslaughterhouse.protobuf.PartList.Builder builderForValue) {
      if (partsBuilder_ == null) {
        parts_ = builderForValue.build();
        onChanged();
      } else {
        partsBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.slaughterhouse.grpc.PartList parts = 4;</code>
     */
    public Builder mergeParts(via.sdj3.grpcslaughterhouse.protobuf.PartList value) {
      if (partsBuilder_ == null) {
        if (parts_ != null) {
          parts_ =
            via.sdj3.grpcslaughterhouse.protobuf.PartList.newBuilder(parts_).mergeFrom(value).buildPartial();
        } else {
          parts_ = value;
        }
        onChanged();
      } else {
        partsBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.slaughterhouse.grpc.PartList parts = 4;</code>
     */
    public Builder clearParts() {
      if (partsBuilder_ == null) {
        parts_ = null;
        onChanged();
      } else {
        parts_ = null;
        partsBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.slaughterhouse.grpc.PartList parts = 4;</code>
     */
    public via.sdj3.grpcslaughterhouse.protobuf.PartList.Builder getPartsBuilder() {
      
      onChanged();
      return getPartsFieldBuilder().getBuilder();
    }
    /**
     * <code>.slaughterhouse.grpc.PartList parts = 4;</code>
     */
    public via.sdj3.grpcslaughterhouse.protobuf.PartListOrBuilder getPartsOrBuilder() {
      if (partsBuilder_ != null) {
        return partsBuilder_.getMessageOrBuilder();
      } else {
        return parts_ == null ?
            via.sdj3.grpcslaughterhouse.protobuf.PartList.getDefaultInstance() : parts_;
      }
    }
    /**
     * <code>.slaughterhouse.grpc.PartList parts = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        via.sdj3.grpcslaughterhouse.protobuf.PartList, via.sdj3.grpcslaughterhouse.protobuf.PartList.Builder, via.sdj3.grpcslaughterhouse.protobuf.PartListOrBuilder> 
        getPartsFieldBuilder() {
      if (partsBuilder_ == null) {
        partsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            via.sdj3.grpcslaughterhouse.protobuf.PartList, via.sdj3.grpcslaughterhouse.protobuf.PartList.Builder, via.sdj3.grpcslaughterhouse.protobuf.PartListOrBuilder>(
                getParts(),
                getParentForChildren(),
                isClean());
        parts_ = null;
      }
      return partsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:slaughterhouse.grpc.TrayMsg)
  }

  // @@protoc_insertion_point(class_scope:slaughterhouse.grpc.TrayMsg)
  private static final via.sdj3.grpcslaughterhouse.protobuf.TrayMsg DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new via.sdj3.grpcslaughterhouse.protobuf.TrayMsg();
  }

  public static via.sdj3.grpcslaughterhouse.protobuf.TrayMsg getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TrayMsg>
      PARSER = new com.google.protobuf.AbstractParser<TrayMsg>() {
    @java.lang.Override
    public TrayMsg parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TrayMsg(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TrayMsg> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TrayMsg> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public via.sdj3.grpcslaughterhouse.protobuf.TrayMsg getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

