// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RecallService.proto

package via.sdj3.grpcslaughterhouse.protobuf;

public interface TrayMsgOrBuilder extends
    // @@protoc_insertion_point(interface_extends:slaughterhouse.grpc.TrayMsg)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 trayId = 1;</code>
   * @return The trayId.
   */
  int getTrayId();

  /**
   * <code>float weightCapacity = 2;</code>
   * @return The weightCapacity.
   */
  float getWeightCapacity();

  /**
   * <code>string partName = 3;</code>
   * @return The partName.
   */
  java.lang.String getPartName();
  /**
   * <code>string partName = 3;</code>
   * @return The bytes for partName.
   */
  com.google.protobuf.ByteString
      getPartNameBytes();

  /**
   * <code>.slaughterhouse.grpc.PartList parts = 4;</code>
   * @return Whether the parts field is set.
   */
  boolean hasParts();
  /**
   * <code>.slaughterhouse.grpc.PartList parts = 4;</code>
   * @return The parts.
   */
  via.sdj3.grpcslaughterhouse.protobuf.PartList getParts();
  /**
   * <code>.slaughterhouse.grpc.PartList parts = 4;</code>
   */
  via.sdj3.grpcslaughterhouse.protobuf.PartListOrBuilder getPartsOrBuilder();
}
