// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RecallService.proto

package via.sdj3.grpcslaughterhouse.protobuf;

public interface TrayListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:slaughterhouse.grpc.TrayList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .slaughterhouse.grpc.TrayMsg trays = 1;</code>
   */
  java.util.List<via.sdj3.grpcslaughterhouse.protobuf.TrayMsg> 
      getTraysList();
  /**
   * <code>repeated .slaughterhouse.grpc.TrayMsg trays = 1;</code>
   */
  via.sdj3.grpcslaughterhouse.protobuf.TrayMsg getTrays(int index);
  /**
   * <code>repeated .slaughterhouse.grpc.TrayMsg trays = 1;</code>
   */
  int getTraysCount();
  /**
   * <code>repeated .slaughterhouse.grpc.TrayMsg trays = 1;</code>
   */
  java.util.List<? extends via.sdj3.grpcslaughterhouse.protobuf.TrayMsgOrBuilder> 
      getTraysOrBuilderList();
  /**
   * <code>repeated .slaughterhouse.grpc.TrayMsg trays = 1;</code>
   */
  via.sdj3.grpcslaughterhouse.protobuf.TrayMsgOrBuilder getTraysOrBuilder(
      int index);
}
